// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIy_BIcprNp2wLAXw3P5obK2AZ85vSRY',
    appId: '1:89647894773:web:5e71a7eb84f6419321b5bc',
    messagingSenderId: '89647894773',
    projectId: 'speakeval-2a29e',
    authDomain: 'speakeval-2a29e.firebaseapp.com',
    storageBucket: 'speakeval-2a29e.firebasestorage.app',
    measurementId: 'G-QP9Y0JH6WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEI3FiWW654vMqBHaZr9dbfwkSz7tqOY',
    appId: '1:89647894773:android:cbc56f4b095dd19721b5bc',
    messagingSenderId: '89647894773',
    projectId: 'speakeval-2a29e',
    storageBucket: 'speakeval-2a29e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-oGVyoWhnOnA8Ru4cjXG4he4KtbMk2_w',
    appId: '1:89647894773:ios:046086b625a8647921b5bc',
    messagingSenderId: '89647894773',
    projectId: 'speakeval-2a29e',
    storageBucket: 'speakeval-2a29e.firebasestorage.app',
    iosBundleId: 'com.example.speakeval',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-oGVyoWhnOnA8Ru4cjXG4he4KtbMk2_w',
    appId: '1:89647894773:ios:046086b625a8647921b5bc',
    messagingSenderId: '89647894773',
    projectId: 'speakeval-2a29e',
    storageBucket: 'speakeval-2a29e.firebasestorage.app',
    iosBundleId: 'com.example.speakeval',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmIy_BIcprNp2wLAXw3P5obK2AZ85vSRY',
    appId: '1:89647894773:web:5aaef8df0231903b21b5bc',
    messagingSenderId: '89647894773',
    projectId: 'speakeval-2a29e',
    authDomain: 'speakeval-2a29e.firebaseapp.com',
    storageBucket: 'speakeval-2a29e.firebasestorage.app',
    measurementId: 'G-ESHZCRPE83',
  );
}
